/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	versioned "github.com/loxilb-io/kube-loxilb/pkg/bgp-client/clientset/versioned"
	internalinterfaces "github.com/loxilb-io/kube-loxilb/pkg/bgp-client/informers/externalversions/internalinterfaces"
	v1 "github.com/loxilb-io/kube-loxilb/pkg/bgp-client/listers/bgppolicydefinition/v1"
	bgppolicydefinitionv1 "github.com/loxilb-io/kube-loxilb/pkg/crds/bgppolicydefinition/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// BGPPolicyDefinitionServiceInformer provides access to a shared informer and lister for
// BGPPolicyDefinitionServices.
type BGPPolicyDefinitionServiceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.BGPPolicyDefinitionServiceLister
}

type bGPPolicyDefinitionServiceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewBGPPolicyDefinitionServiceInformer constructs a new informer for BGPPolicyDefinitionService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBGPPolicyDefinitionServiceInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredBGPPolicyDefinitionServiceInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredBGPPolicyDefinitionServiceInformer constructs a new informer for BGPPolicyDefinitionService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredBGPPolicyDefinitionServiceInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BgppolicydefinitionV1().BGPPolicyDefinitionServices().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BgppolicydefinitionV1().BGPPolicyDefinitionServices().Watch(context.TODO(), options)
			},
		},
		&bgppolicydefinitionv1.BGPPolicyDefinitionService{},
		resyncPeriod,
		indexers,
	)
}

func (f *bGPPolicyDefinitionServiceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredBGPPolicyDefinitionServiceInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *bGPPolicyDefinitionServiceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&bgppolicydefinitionv1.BGPPolicyDefinitionService{}, f.defaultInformer)
}

func (f *bGPPolicyDefinitionServiceInformer) Lister() v1.BGPPolicyDefinitionServiceLister {
	return v1.NewBGPPolicyDefinitionServiceLister(f.Informer().GetIndexer())
}
