//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright (c) NetLOX Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	api "github.com/loxilb-io/kube-loxilb/pkg/api"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPPolicyDefinedSetsModel) DeepCopyInto(out *BGPPolicyDefinedSetsModel) {
	*out = *in
	if in.List != nil {
		in, out := &in.List, &out.List
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PrefixList != nil {
		in, out := &in.PrefixList, &out.PrefixList
		*out = make([]api.Prefix, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPPolicyDefinedSetsModel.
func (in *BGPPolicyDefinedSetsModel) DeepCopy() *BGPPolicyDefinedSetsModel {
	if in == nil {
		return nil
	}
	out := new(BGPPolicyDefinedSetsModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPPolicyDefinedSetsService) DeepCopyInto(out *BGPPolicyDefinedSetsService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPPolicyDefinedSetsService.
func (in *BGPPolicyDefinedSetsService) DeepCopy() *BGPPolicyDefinedSetsService {
	if in == nil {
		return nil
	}
	out := new(BGPPolicyDefinedSetsService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BGPPolicyDefinedSetsService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPPolicyDefinedSetsServiceList) DeepCopyInto(out *BGPPolicyDefinedSetsServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]*BGPPolicyDefinedSetsService, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(BGPPolicyDefinedSetsService)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPPolicyDefinedSetsServiceList.
func (in *BGPPolicyDefinedSetsServiceList) DeepCopy() *BGPPolicyDefinedSetsServiceList {
	if in == nil {
		return nil
	}
	out := new(BGPPolicyDefinedSetsServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BGPPolicyDefinedSetsServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPPolicyDefinedSetsServiceStatus) DeepCopyInto(out *BGPPolicyDefinedSetsServiceStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPPolicyDefinedSetsServiceStatus.
func (in *BGPPolicyDefinedSetsServiceStatus) DeepCopy() *BGPPolicyDefinedSetsServiceStatus {
	if in == nil {
		return nil
	}
	out := new(BGPPolicyDefinedSetsServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPPolicyDefinedSetsSpec) DeepCopyInto(out *BGPPolicyDefinedSetsSpec) {
	*out = *in
	in.Model.DeepCopyInto(&out.Model)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPPolicyDefinedSetsSpec.
func (in *BGPPolicyDefinedSetsSpec) DeepCopy() *BGPPolicyDefinedSetsSpec {
	if in == nil {
		return nil
	}
	out := new(BGPPolicyDefinedSetsSpec)
	in.DeepCopyInto(out)
	return out
}
