/*
Copyright (c) NetLOX Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	crdsegressv1 "github.com/loxilb-io/kube-loxilb/pkg/crds/egress/v1"
	versioned "github.com/loxilb-io/kube-loxilb/pkg/egress-client/clientset/versioned"
	internalinterfaces "github.com/loxilb-io/kube-loxilb/pkg/egress-client/informers/externalversions/internalinterfaces"
	egressv1 "github.com/loxilb-io/kube-loxilb/pkg/egress-client/listers/egress/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// EgressInformer provides access to a shared informer and lister for
// Egresses.
type EgressInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() egressv1.EgressLister
}

type egressInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewEgressInformer constructs a new informer for Egress type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewEgressInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredEgressInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredEgressInformer constructs a new informer for Egress type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredEgressInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EgressV1().Egresses(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EgressV1().Egresses(namespace).Watch(context.TODO(), options)
			},
		},
		&crdsegressv1.Egress{},
		resyncPeriod,
		indexers,
	)
}

func (f *egressInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredEgressInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *egressInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&crdsegressv1.Egress{}, f.defaultInformer)
}

func (f *egressInformer) Lister() egressv1.EgressLister {
	return egressv1.NewEgressLister(f.Informer().GetIndexer())
}
