/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	versioned "github.com/loxilb-io/kube-loxilb/pkg/bgp-client/clientset/versioned"
	internalinterfaces "github.com/loxilb-io/kube-loxilb/pkg/bgp-client/informers/externalversions/internalinterfaces"
	v1 "github.com/loxilb-io/kube-loxilb/pkg/bgp-client/listers/bgppeer/v1"
	bgppeerv1 "github.com/loxilb-io/kube-loxilb/pkg/crds/bgppeer/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// BGPPeerServiceInformer provides access to a shared informer and lister for
// BGPPeerServices.
type BGPPeerServiceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.BGPPeerServiceLister
}

type bGPPeerServiceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewBGPPeerServiceInformer constructs a new informer for BGPPeerService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBGPPeerServiceInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredBGPPeerServiceInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredBGPPeerServiceInformer constructs a new informer for BGPPeerService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredBGPPeerServiceInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BgppeerV1().BGPPeerServices().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BgppeerV1().BGPPeerServices().Watch(context.TODO(), options)
			},
		},
		&bgppeerv1.BGPPeerService{},
		resyncPeriod,
		indexers,
	)
}

func (f *bGPPeerServiceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredBGPPeerServiceInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *bGPPeerServiceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&bgppeerv1.BGPPeerService{}, f.defaultInformer)
}

func (f *bGPPeerServiceInformer) Lister() v1.BGPPeerServiceLister {
	return v1.NewBGPPeerServiceLister(f.Informer().GetIndexer())
}
