/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// BGPAsPathSetApplyConfiguration represents an declarative configuration of the BGPAsPathSet type for use
// with apply.
type BGPAsPathSetApplyConfiguration struct {
	AsPathSet       *string `json:"asPathSet,omitempty"`
	MatchSetOptions *string `json:"matchSetOptions,omitempty"`
}

// BGPAsPathSetApplyConfiguration constructs an declarative configuration of the BGPAsPathSet type for use with
// apply.
func BGPAsPathSet() *BGPAsPathSetApplyConfiguration {
	return &BGPAsPathSetApplyConfiguration{}
}

// WithAsPathSet sets the AsPathSet field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AsPathSet field is set to the value of the last call.
func (b *BGPAsPathSetApplyConfiguration) WithAsPathSet(value string) *BGPAsPathSetApplyConfiguration {
	b.AsPathSet = &value
	return b
}

// WithMatchSetOptions sets the MatchSetOptions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MatchSetOptions field is set to the value of the last call.
func (b *BGPAsPathSetApplyConfiguration) WithMatchSetOptions(value string) *BGPAsPathSetApplyConfiguration {
	b.MatchSetOptions = &value
	return b
}
