/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ConditionsApplyConfiguration represents an declarative configuration of the Conditions type for use
// with apply.
type ConditionsApplyConfiguration struct {
	PrefixSet     *MatchPrefixSetApplyConfiguration   `json:"matchPrefixSet,omitempty"`
	NeighborSet   *MatchNeighborSetApplyConfiguration `json:"matchNeighborSet,omitempty"`
	BGPConditions *BGPConditionsApplyConfiguration    `json:"bgpConditions,omitempty"`
}

// ConditionsApplyConfiguration constructs an declarative configuration of the Conditions type for use with
// apply.
func Conditions() *ConditionsApplyConfiguration {
	return &ConditionsApplyConfiguration{}
}

// WithPrefixSet sets the PrefixSet field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrefixSet field is set to the value of the last call.
func (b *ConditionsApplyConfiguration) WithPrefixSet(value *MatchPrefixSetApplyConfiguration) *ConditionsApplyConfiguration {
	b.PrefixSet = value
	return b
}

// WithNeighborSet sets the NeighborSet field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NeighborSet field is set to the value of the last call.
func (b *ConditionsApplyConfiguration) WithNeighborSet(value *MatchNeighborSetApplyConfiguration) *ConditionsApplyConfiguration {
	b.NeighborSet = value
	return b
}

// WithBGPConditions sets the BGPConditions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BGPConditions field is set to the value of the last call.
func (b *ConditionsApplyConfiguration) WithBGPConditions(value *BGPConditionsApplyConfiguration) *ConditionsApplyConfiguration {
	b.BGPConditions = value
	return b
}
