/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// StatementApplyConfiguration represents an declarative configuration of the Statement type for use
// with apply.
type StatementApplyConfiguration struct {
	Name       *string                       `json:"name,omitempty"`
	Conditions *ConditionsApplyConfiguration `json:"conditions,omitempty"`
	Actions    *ActionsApplyConfiguration    `json:"actions,omitempty"`
}

// StatementApplyConfiguration constructs an declarative configuration of the Statement type for use with
// apply.
func Statement() *StatementApplyConfiguration {
	return &StatementApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *StatementApplyConfiguration) WithName(value string) *StatementApplyConfiguration {
	b.Name = &value
	return b
}

// WithConditions sets the Conditions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Conditions field is set to the value of the last call.
func (b *StatementApplyConfiguration) WithConditions(value *ConditionsApplyConfiguration) *StatementApplyConfiguration {
	b.Conditions = value
	return b
}

// WithActions sets the Actions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Actions field is set to the value of the last call.
func (b *StatementApplyConfiguration) WithActions(value *ActionsApplyConfiguration) *StatementApplyConfiguration {
	b.Actions = value
	return b
}
