/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	bgppolicydefinedsetsv1 "github.com/loxilb-io/kube-loxilb/pkg/client/applyconfiguration/bgppolicydefinedsets/v1"
	v1 "github.com/loxilb-io/kube-loxilb/pkg/crds/bgppolicydefinedsets/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBGPPolicyDefinedSetsServices implements BGPPolicyDefinedSetsServiceInterface
type FakeBGPPolicyDefinedSetsServices struct {
	Fake *FakeBgppolicydefinedsetsV1
}

var bgppolicydefinedsetsservicesResource = v1.SchemeGroupVersion.WithResource("bgppolicydefinedsetsservices")

var bgppolicydefinedsetsservicesKind = v1.SchemeGroupVersion.WithKind("BGPPolicyDefinedSetsService")

// Get takes name of the bGPPolicyDefinedSetsService, and returns the corresponding bGPPolicyDefinedSetsService object, and an error if there is any.
func (c *FakeBGPPolicyDefinedSetsServices) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.BGPPolicyDefinedSetsService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(bgppolicydefinedsetsservicesResource, name), &v1.BGPPolicyDefinedSetsService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.BGPPolicyDefinedSetsService), err
}

// List takes label and field selectors, and returns the list of BGPPolicyDefinedSetsServices that match those selectors.
func (c *FakeBGPPolicyDefinedSetsServices) List(ctx context.Context, opts metav1.ListOptions) (result *v1.BGPPolicyDefinedSetsServiceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(bgppolicydefinedsetsservicesResource, bgppolicydefinedsetsservicesKind, opts), &v1.BGPPolicyDefinedSetsServiceList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.BGPPolicyDefinedSetsServiceList{ListMeta: obj.(*v1.BGPPolicyDefinedSetsServiceList).ListMeta}
	for _, item := range obj.(*v1.BGPPolicyDefinedSetsServiceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested bGPPolicyDefinedSetsServices.
func (c *FakeBGPPolicyDefinedSetsServices) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(bgppolicydefinedsetsservicesResource, opts))
}

// Create takes the representation of a bGPPolicyDefinedSetsService and creates it.  Returns the server's representation of the bGPPolicyDefinedSetsService, and an error, if there is any.
func (c *FakeBGPPolicyDefinedSetsServices) Create(ctx context.Context, bGPPolicyDefinedSetsService *v1.BGPPolicyDefinedSetsService, opts metav1.CreateOptions) (result *v1.BGPPolicyDefinedSetsService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(bgppolicydefinedsetsservicesResource, bGPPolicyDefinedSetsService), &v1.BGPPolicyDefinedSetsService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.BGPPolicyDefinedSetsService), err
}

// Update takes the representation of a bGPPolicyDefinedSetsService and updates it. Returns the server's representation of the bGPPolicyDefinedSetsService, and an error, if there is any.
func (c *FakeBGPPolicyDefinedSetsServices) Update(ctx context.Context, bGPPolicyDefinedSetsService *v1.BGPPolicyDefinedSetsService, opts metav1.UpdateOptions) (result *v1.BGPPolicyDefinedSetsService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(bgppolicydefinedsetsservicesResource, bGPPolicyDefinedSetsService), &v1.BGPPolicyDefinedSetsService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.BGPPolicyDefinedSetsService), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBGPPolicyDefinedSetsServices) UpdateStatus(ctx context.Context, bGPPolicyDefinedSetsService *v1.BGPPolicyDefinedSetsService, opts metav1.UpdateOptions) (*v1.BGPPolicyDefinedSetsService, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(bgppolicydefinedsetsservicesResource, "status", bGPPolicyDefinedSetsService), &v1.BGPPolicyDefinedSetsService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.BGPPolicyDefinedSetsService), err
}

// Delete takes name of the bGPPolicyDefinedSetsService and deletes it. Returns an error if one occurs.
func (c *FakeBGPPolicyDefinedSetsServices) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(bgppolicydefinedsetsservicesResource, name, opts), &v1.BGPPolicyDefinedSetsService{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBGPPolicyDefinedSetsServices) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(bgppolicydefinedsetsservicesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1.BGPPolicyDefinedSetsServiceList{})
	return err
}

// Patch applies the patch and returns the patched bGPPolicyDefinedSetsService.
func (c *FakeBGPPolicyDefinedSetsServices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.BGPPolicyDefinedSetsService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(bgppolicydefinedsetsservicesResource, name, pt, data, subresources...), &v1.BGPPolicyDefinedSetsService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.BGPPolicyDefinedSetsService), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied bGPPolicyDefinedSetsService.
func (c *FakeBGPPolicyDefinedSetsServices) Apply(ctx context.Context, bGPPolicyDefinedSetsService *bgppolicydefinedsetsv1.BGPPolicyDefinedSetsServiceApplyConfiguration, opts metav1.ApplyOptions) (result *v1.BGPPolicyDefinedSetsService, err error) {
	if bGPPolicyDefinedSetsService == nil {
		return nil, fmt.Errorf("bGPPolicyDefinedSetsService provided to Apply must not be nil")
	}
	data, err := json.Marshal(bGPPolicyDefinedSetsService)
	if err != nil {
		return nil, err
	}
	name := bGPPolicyDefinedSetsService.Name
	if name == nil {
		return nil, fmt.Errorf("bGPPolicyDefinedSetsService.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(bgppolicydefinedsetsservicesResource, *name, types.ApplyPatchType, data), &v1.BGPPolicyDefinedSetsService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.BGPPolicyDefinedSetsService), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeBGPPolicyDefinedSetsServices) ApplyStatus(ctx context.Context, bGPPolicyDefinedSetsService *bgppolicydefinedsetsv1.BGPPolicyDefinedSetsServiceApplyConfiguration, opts metav1.ApplyOptions) (result *v1.BGPPolicyDefinedSetsService, err error) {
	if bGPPolicyDefinedSetsService == nil {
		return nil, fmt.Errorf("bGPPolicyDefinedSetsService provided to Apply must not be nil")
	}
	data, err := json.Marshal(bGPPolicyDefinedSetsService)
	if err != nil {
		return nil, err
	}
	name := bGPPolicyDefinedSetsService.Name
	if name == nil {
		return nil, fmt.Errorf("bGPPolicyDefinedSetsService.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(bgppolicydefinedsetsservicesResource, *name, types.ApplyPatchType, data, "status"), &v1.BGPPolicyDefinedSetsService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.BGPPolicyDefinedSetsService), err
}
