/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	versioned "github.com/loxilb-io/kube-loxilb/pkg/bgp-client/clientset/versioned"
	internalinterfaces "github.com/loxilb-io/kube-loxilb/pkg/bgp-client/informers/externalversions/internalinterfaces"
	v1 "github.com/loxilb-io/kube-loxilb/pkg/bgp-client/listers/bgppolicyapply/v1"
	bgppolicyapplyv1 "github.com/loxilb-io/kube-loxilb/pkg/crds/bgppolicyapply/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// BGPPolicyApplyServiceInformer provides access to a shared informer and lister for
// BGPPolicyApplyServices.
type BGPPolicyApplyServiceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.BGPPolicyApplyServiceLister
}

type bGPPolicyApplyServiceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewBGPPolicyApplyServiceInformer constructs a new informer for BGPPolicyApplyService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBGPPolicyApplyServiceInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredBGPPolicyApplyServiceInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredBGPPolicyApplyServiceInformer constructs a new informer for BGPPolicyApplyService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredBGPPolicyApplyServiceInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BgppolicyapplyV1().BGPPolicyApplyServices().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BgppolicyapplyV1().BGPPolicyApplyServices().Watch(context.TODO(), options)
			},
		},
		&bgppolicyapplyv1.BGPPolicyApplyService{},
		resyncPeriod,
		indexers,
	)
}

func (f *bGPPolicyApplyServiceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredBGPPolicyApplyServiceInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *bGPPolicyApplyServiceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&bgppolicyapplyv1.BGPPolicyApplyService{}, f.defaultInformer)
}

func (f *bGPPolicyApplyServiceInformer) Lister() v1.BGPPolicyApplyServiceLister {
	return v1.NewBGPPolicyApplyServiceLister(f.Informer().GetIndexer())
}
