/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	api "github.com/loxilb-io/kube-loxilb/pkg/api"
)

// BGPPolicyDefinedSetsModelApplyConfiguration represents an declarative configuration of the BGPPolicyDefinedSetsModel type for use
// with apply.
type BGPPolicyDefinedSetsModelApplyConfiguration struct {
	Name        *string      `json:"name,omitempty"`
	DefinedType *string      `json:"definedType,omitempty"`
	List        []string     `json:"List,omitempty"`
	PrefixList  []api.Prefix `json:"prefixList,omitempty"`
}

// BGPPolicyDefinedSetsModelApplyConfiguration constructs an declarative configuration of the BGPPolicyDefinedSetsModel type for use with
// apply.
func BGPPolicyDefinedSetsModel() *BGPPolicyDefinedSetsModelApplyConfiguration {
	return &BGPPolicyDefinedSetsModelApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *BGPPolicyDefinedSetsModelApplyConfiguration) WithName(value string) *BGPPolicyDefinedSetsModelApplyConfiguration {
	b.Name = &value
	return b
}

// WithDefinedType sets the DefinedType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefinedType field is set to the value of the last call.
func (b *BGPPolicyDefinedSetsModelApplyConfiguration) WithDefinedType(value string) *BGPPolicyDefinedSetsModelApplyConfiguration {
	b.DefinedType = &value
	return b
}

// WithList adds the given value to the List field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the List field.
func (b *BGPPolicyDefinedSetsModelApplyConfiguration) WithList(values ...string) *BGPPolicyDefinedSetsModelApplyConfiguration {
	for i := range values {
		b.List = append(b.List, values[i])
	}
	return b
}

// WithPrefixList adds the given value to the PrefixList field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PrefixList field.
func (b *BGPPolicyDefinedSetsModelApplyConfiguration) WithPrefixList(values ...api.Prefix) *BGPPolicyDefinedSetsModelApplyConfiguration {
	for i := range values {
		b.PrefixList = append(b.PrefixList, values[i])
	}
	return b
}
