/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	bgppolicyapplyv1 "github.com/loxilb-io/kube-loxilb/pkg/bgp-client/applyconfiguration/bgppolicyapply/v1"
	scheme "github.com/loxilb-io/kube-loxilb/pkg/bgp-client/clientset/versioned/scheme"
	v1 "github.com/loxilb-io/kube-loxilb/pkg/crds/bgppolicyapply/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// BGPPolicyApplyServicesGetter has a method to return a BGPPolicyApplyServiceInterface.
// A group's client should implement this interface.
type BGPPolicyApplyServicesGetter interface {
	BGPPolicyApplyServices() BGPPolicyApplyServiceInterface
}

// BGPPolicyApplyServiceInterface has methods to work with BGPPolicyApplyService resources.
type BGPPolicyApplyServiceInterface interface {
	Create(ctx context.Context, bGPPolicyApplyService *v1.BGPPolicyApplyService, opts metav1.CreateOptions) (*v1.BGPPolicyApplyService, error)
	Update(ctx context.Context, bGPPolicyApplyService *v1.BGPPolicyApplyService, opts metav1.UpdateOptions) (*v1.BGPPolicyApplyService, error)
	UpdateStatus(ctx context.Context, bGPPolicyApplyService *v1.BGPPolicyApplyService, opts metav1.UpdateOptions) (*v1.BGPPolicyApplyService, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.BGPPolicyApplyService, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.BGPPolicyApplyServiceList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.BGPPolicyApplyService, err error)
	Apply(ctx context.Context, bGPPolicyApplyService *bgppolicyapplyv1.BGPPolicyApplyServiceApplyConfiguration, opts metav1.ApplyOptions) (result *v1.BGPPolicyApplyService, err error)
	ApplyStatus(ctx context.Context, bGPPolicyApplyService *bgppolicyapplyv1.BGPPolicyApplyServiceApplyConfiguration, opts metav1.ApplyOptions) (result *v1.BGPPolicyApplyService, err error)
	BGPPolicyApplyServiceExpansion
}

// bGPPolicyApplyServices implements BGPPolicyApplyServiceInterface
type bGPPolicyApplyServices struct {
	client rest.Interface
}

// newBGPPolicyApplyServices returns a BGPPolicyApplyServices
func newBGPPolicyApplyServices(c *BgppolicyapplyV1Client) *bGPPolicyApplyServices {
	return &bGPPolicyApplyServices{
		client: c.RESTClient(),
	}
}

// Get takes name of the bGPPolicyApplyService, and returns the corresponding bGPPolicyApplyService object, and an error if there is any.
func (c *bGPPolicyApplyServices) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.BGPPolicyApplyService, err error) {
	result = &v1.BGPPolicyApplyService{}
	err = c.client.Get().
		Resource("bgppolicyapplyservices").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of BGPPolicyApplyServices that match those selectors.
func (c *bGPPolicyApplyServices) List(ctx context.Context, opts metav1.ListOptions) (result *v1.BGPPolicyApplyServiceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.BGPPolicyApplyServiceList{}
	err = c.client.Get().
		Resource("bgppolicyapplyservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested bGPPolicyApplyServices.
func (c *bGPPolicyApplyServices) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("bgppolicyapplyservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a bGPPolicyApplyService and creates it.  Returns the server's representation of the bGPPolicyApplyService, and an error, if there is any.
func (c *bGPPolicyApplyServices) Create(ctx context.Context, bGPPolicyApplyService *v1.BGPPolicyApplyService, opts metav1.CreateOptions) (result *v1.BGPPolicyApplyService, err error) {
	result = &v1.BGPPolicyApplyService{}
	err = c.client.Post().
		Resource("bgppolicyapplyservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(bGPPolicyApplyService).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a bGPPolicyApplyService and updates it. Returns the server's representation of the bGPPolicyApplyService, and an error, if there is any.
func (c *bGPPolicyApplyServices) Update(ctx context.Context, bGPPolicyApplyService *v1.BGPPolicyApplyService, opts metav1.UpdateOptions) (result *v1.BGPPolicyApplyService, err error) {
	result = &v1.BGPPolicyApplyService{}
	err = c.client.Put().
		Resource("bgppolicyapplyservices").
		Name(bGPPolicyApplyService.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(bGPPolicyApplyService).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *bGPPolicyApplyServices) UpdateStatus(ctx context.Context, bGPPolicyApplyService *v1.BGPPolicyApplyService, opts metav1.UpdateOptions) (result *v1.BGPPolicyApplyService, err error) {
	result = &v1.BGPPolicyApplyService{}
	err = c.client.Put().
		Resource("bgppolicyapplyservices").
		Name(bGPPolicyApplyService.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(bGPPolicyApplyService).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the bGPPolicyApplyService and deletes it. Returns an error if one occurs.
func (c *bGPPolicyApplyServices) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("bgppolicyapplyservices").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *bGPPolicyApplyServices) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("bgppolicyapplyservices").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched bGPPolicyApplyService.
func (c *bGPPolicyApplyServices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.BGPPolicyApplyService, err error) {
	result = &v1.BGPPolicyApplyService{}
	err = c.client.Patch(pt).
		Resource("bgppolicyapplyservices").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied bGPPolicyApplyService.
func (c *bGPPolicyApplyServices) Apply(ctx context.Context, bGPPolicyApplyService *bgppolicyapplyv1.BGPPolicyApplyServiceApplyConfiguration, opts metav1.ApplyOptions) (result *v1.BGPPolicyApplyService, err error) {
	if bGPPolicyApplyService == nil {
		return nil, fmt.Errorf("bGPPolicyApplyService provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(bGPPolicyApplyService)
	if err != nil {
		return nil, err
	}
	name := bGPPolicyApplyService.Name
	if name == nil {
		return nil, fmt.Errorf("bGPPolicyApplyService.Name must be provided to Apply")
	}
	result = &v1.BGPPolicyApplyService{}
	err = c.client.Patch(types.ApplyPatchType).
		Resource("bgppolicyapplyservices").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *bGPPolicyApplyServices) ApplyStatus(ctx context.Context, bGPPolicyApplyService *bgppolicyapplyv1.BGPPolicyApplyServiceApplyConfiguration, opts metav1.ApplyOptions) (result *v1.BGPPolicyApplyService, err error) {
	if bGPPolicyApplyService == nil {
		return nil, fmt.Errorf("bGPPolicyApplyService provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(bGPPolicyApplyService)
	if err != nil {
		return nil, err
	}

	name := bGPPolicyApplyService.Name
	if name == nil {
		return nil, fmt.Errorf("bGPPolicyApplyService.Name must be provided to Apply")
	}

	result = &v1.BGPPolicyApplyService{}
	err = c.client.Patch(types.ApplyPatchType).
		Resource("bgppolicyapplyservices").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
