//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Actions) DeepCopyInto(out *Actions) {
	*out = *in
	in.BGPActions.DeepCopyInto(&out.BGPActions)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Actions.
func (in *Actions) DeepCopy() *Actions {
	if in == nil {
		return nil
	}
	out := new(Actions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPActions) DeepCopyInto(out *BGPActions) {
	*out = *in
	in.SetCommunity.DeepCopyInto(&out.SetCommunity)
	in.SetExtCommunity.DeepCopyInto(&out.SetExtCommunity)
	in.SetLargeCommunity.DeepCopyInto(&out.SetLargeCommunity)
	out.SetAsPathPrepend = in.SetAsPathPrepend
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPActions.
func (in *BGPActions) DeepCopy() *BGPActions {
	if in == nil {
		return nil
	}
	out := new(BGPActions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPAsPathLength) DeepCopyInto(out *BGPAsPathLength) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPAsPathLength.
func (in *BGPAsPathLength) DeepCopy() *BGPAsPathLength {
	if in == nil {
		return nil
	}
	out := new(BGPAsPathLength)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPAsPathSet) DeepCopyInto(out *BGPAsPathSet) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPAsPathSet.
func (in *BGPAsPathSet) DeepCopy() *BGPAsPathSet {
	if in == nil {
		return nil
	}
	out := new(BGPAsPathSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPCommunitySet) DeepCopyInto(out *BGPCommunitySet) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPCommunitySet.
func (in *BGPCommunitySet) DeepCopy() *BGPCommunitySet {
	if in == nil {
		return nil
	}
	out := new(BGPCommunitySet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPConditions) DeepCopyInto(out *BGPConditions) {
	*out = *in
	if in.AfiSafiIn != nil {
		in, out := &in.AfiSafiIn, &out.AfiSafiIn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.AsPathSet = in.AsPathSet
	out.AsPathLength = in.AsPathLength
	out.CommunitySet = in.CommunitySet
	out.ExtCommunitySet = in.ExtCommunitySet
	out.LargeCommunitySet = in.LargeCommunitySet
	if in.NextHopInList != nil {
		in, out := &in.NextHopInList, &out.NextHopInList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPConditions.
func (in *BGPConditions) DeepCopy() *BGPConditions {
	if in == nil {
		return nil
	}
	out := new(BGPConditions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPPolicyDefinition) DeepCopyInto(out *BGPPolicyDefinition) {
	*out = *in
	if in.Statement != nil {
		in, out := &in.Statement, &out.Statement
		*out = make([]Statement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPPolicyDefinition.
func (in *BGPPolicyDefinition) DeepCopy() *BGPPolicyDefinition {
	if in == nil {
		return nil
	}
	out := new(BGPPolicyDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPPolicyDefinitionService) DeepCopyInto(out *BGPPolicyDefinitionService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPPolicyDefinitionService.
func (in *BGPPolicyDefinitionService) DeepCopy() *BGPPolicyDefinitionService {
	if in == nil {
		return nil
	}
	out := new(BGPPolicyDefinitionService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BGPPolicyDefinitionService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPPolicyDefinitionServiceList) DeepCopyInto(out *BGPPolicyDefinitionServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]*BGPPolicyDefinitionService, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(BGPPolicyDefinitionService)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPPolicyDefinitionServiceList.
func (in *BGPPolicyDefinitionServiceList) DeepCopy() *BGPPolicyDefinitionServiceList {
	if in == nil {
		return nil
	}
	out := new(BGPPolicyDefinitionServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BGPPolicyDefinitionServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPPolicyDefinitionServiceStatus) DeepCopyInto(out *BGPPolicyDefinitionServiceStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPPolicyDefinitionServiceStatus.
func (in *BGPPolicyDefinitionServiceStatus) DeepCopy() *BGPPolicyDefinitionServiceStatus {
	if in == nil {
		return nil
	}
	out := new(BGPPolicyDefinitionServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Conditions) DeepCopyInto(out *Conditions) {
	*out = *in
	out.PrefixSet = in.PrefixSet
	out.NeighborSet = in.NeighborSet
	in.BGPConditions.DeepCopyInto(&out.BGPConditions)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Conditions.
func (in *Conditions) DeepCopy() *Conditions {
	if in == nil {
		return nil
	}
	out := new(Conditions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchNeighborSet) DeepCopyInto(out *MatchNeighborSet) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchNeighborSet.
func (in *MatchNeighborSet) DeepCopy() *MatchNeighborSet {
	if in == nil {
		return nil
	}
	out := new(MatchNeighborSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchPrefixSet) DeepCopyInto(out *MatchPrefixSet) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchPrefixSet.
func (in *MatchPrefixSet) DeepCopy() *MatchPrefixSet {
	if in == nil {
		return nil
	}
	out := new(MatchPrefixSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SetAsPathPrepend) DeepCopyInto(out *SetAsPathPrepend) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SetAsPathPrepend.
func (in *SetAsPathPrepend) DeepCopy() *SetAsPathPrepend {
	if in == nil {
		return nil
	}
	out := new(SetAsPathPrepend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SetCommunity) DeepCopyInto(out *SetCommunity) {
	*out = *in
	if in.SetCommunityMethod != nil {
		in, out := &in.SetCommunityMethod, &out.SetCommunityMethod
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SetCommunity.
func (in *SetCommunity) DeepCopy() *SetCommunity {
	if in == nil {
		return nil
	}
	out := new(SetCommunity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Statement) DeepCopyInto(out *Statement) {
	*out = *in
	in.Conditions.DeepCopyInto(&out.Conditions)
	in.Actions.DeepCopyInto(&out.Actions)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Statement.
func (in *Statement) DeepCopy() *Statement {
	if in == nil {
		return nil
	}
	out := new(Statement)
	in.DeepCopyInto(out)
	return out
}
