/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// BGPPeerModelApplyConfiguration represents an declarative configuration of the BGPPeerModel type for use
// with apply.
type BGPPeerModelApplyConfiguration struct {
	IPAddress  *string `json:"ipAddress,omitempty"`
	RemoteAs   *int64  `json:"remoteAs,omitempty"`
	RemotePort *int64  `json:"remotePort,omitempty"`
}

// BGPPeerModelApplyConfiguration constructs an declarative configuration of the BGPPeerModel type for use with
// apply.
func BGPPeerModel() *BGPPeerModelApplyConfiguration {
	return &BGPPeerModelApplyConfiguration{}
}

// WithIPAddress sets the IPAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IPAddress field is set to the value of the last call.
func (b *BGPPeerModelApplyConfiguration) WithIPAddress(value string) *BGPPeerModelApplyConfiguration {
	b.IPAddress = &value
	return b
}

// WithRemoteAs sets the RemoteAs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemoteAs field is set to the value of the last call.
func (b *BGPPeerModelApplyConfiguration) WithRemoteAs(value int64) *BGPPeerModelApplyConfiguration {
	b.RemoteAs = &value
	return b
}

// WithRemotePort sets the RemotePort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemotePort field is set to the value of the last call.
func (b *BGPPeerModelApplyConfiguration) WithRemotePort(value int64) *BGPPeerModelApplyConfiguration {
	b.RemotePort = &value
	return b
}
