/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	versioned "github.com/loxilb-io/kube-loxilb/pkg/client/clientset/versioned"
	internalinterfaces "github.com/loxilb-io/kube-loxilb/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/loxilb-io/kube-loxilb/pkg/client/listers/multiclusterlbservice/v1"
	time "time"

	multiclusterlbservicev1 "github.com/loxilb-io/kube-loxilb/pkg/apis/multiclusterlbservice/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MultiClusterLBServiceInformer provides access to a shared informer and lister for
// MultiClusterLBServices.
type MultiClusterLBServiceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.MultiClusterLBServiceLister
}

type multiClusterLBServiceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewMultiClusterLBServiceInformer constructs a new informer for MultiClusterLBService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMultiClusterLBServiceInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMultiClusterLBServiceInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredMultiClusterLBServiceInformer constructs a new informer for MultiClusterLBService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMultiClusterLBServiceInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MulticlusterV1().MultiClusterLBServices().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MulticlusterV1().MultiClusterLBServices().Watch(context.TODO(), options)
			},
		},
		&multiclusterlbservicev1.MultiClusterLBService{},
		resyncPeriod,
		indexers,
	)
}

func (f *multiClusterLBServiceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMultiClusterLBServiceInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *multiClusterLBServiceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&multiclusterlbservicev1.MultiClusterLBService{}, f.defaultInformer)
}

func (f *multiClusterLBServiceInformer) Lister() v1.MultiClusterLBServiceLister {
	return v1.NewMultiClusterLBServiceLister(f.Informer().GetIndexer())
}
