/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	loxiurlv1 "github.com/loxilb-io/kube-loxilb/pkg/crds/loxiurl/v1"
	scheme "github.com/loxilb-io/kube-loxilb/pkg/klb-client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// LoxiURLsGetter has a method to return a LoxiURLInterface.
// A group's client should implement this interface.
type LoxiURLsGetter interface {
	LoxiURLs() LoxiURLInterface
}

// LoxiURLInterface has methods to work with LoxiURL resources.
type LoxiURLInterface interface {
	Create(ctx context.Context, loxiURL *loxiurlv1.LoxiURL, opts metav1.CreateOptions) (*loxiurlv1.LoxiURL, error)
	Update(ctx context.Context, loxiURL *loxiurlv1.LoxiURL, opts metav1.UpdateOptions) (*loxiurlv1.LoxiURL, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, loxiURL *loxiurlv1.LoxiURL, opts metav1.UpdateOptions) (*loxiurlv1.LoxiURL, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*loxiurlv1.LoxiURL, error)
	List(ctx context.Context, opts metav1.ListOptions) (*loxiurlv1.LoxiURLList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *loxiurlv1.LoxiURL, err error)
	LoxiURLExpansion
}

// loxiURLs implements LoxiURLInterface
type loxiURLs struct {
	*gentype.ClientWithList[*loxiurlv1.LoxiURL, *loxiurlv1.LoxiURLList]
}

// newLoxiURLs returns a LoxiURLs
func newLoxiURLs(c *LoxiurlV1Client) *loxiURLs {
	return &loxiURLs{
		gentype.NewClientWithList[*loxiurlv1.LoxiURL, *loxiurlv1.LoxiURLList](
			"loxiurls",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *loxiurlv1.LoxiURL { return &loxiurlv1.LoxiURL{} },
			func() *loxiurlv1.LoxiURLList { return &loxiurlv1.LoxiURLList{} }),
	}
}
