/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	context "context"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1 "github.com/loxilb-io/kube-loxilb/pkg/klb-crds/loxiurl/v1"
)

// FakeLoxiURLs implements LoxiURLInterface
type FakeLoxiURLs struct {
	Fake *FakeLoxiurlV1
}

var loxiurlsResource = v1.SchemeGroupVersion.WithResource("loxiurls")

var loxiurlsKind = v1.SchemeGroupVersion.WithKind("LoxiURL")

// Get takes name of the loxiURL, and returns the corresponding loxiURL object, and an error if there is any.
func (c *FakeLoxiURLs) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.LoxiURL, err error) {
	emptyResult := &v1.LoxiURL{}
	obj, err := c.Fake.
		Invokes(testing.NewRootGetActionWithOptions(loxiurlsResource, name, options), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.LoxiURL), err
}

// List takes label and field selectors, and returns the list of LoxiURLs that match those selectors.
func (c *FakeLoxiURLs) List(ctx context.Context, opts metav1.ListOptions) (result *v1.LoxiURLList, err error) {
	emptyResult := &v1.LoxiURLList{}
	obj, err := c.Fake.
		Invokes(testing.NewRootListActionWithOptions(loxiurlsResource, loxiurlsKind, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.LoxiURLList{ListMeta: obj.(*v1.LoxiURLList).ListMeta}
	for _, item := range obj.(*v1.LoxiURLList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested loxiURLs.
func (c *FakeLoxiURLs) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchActionWithOptions(loxiurlsResource, opts))
}

// Create takes the representation of a loxiURL and creates it.  Returns the server's representation of the loxiURL, and an error, if there is any.
func (c *FakeLoxiURLs) Create(ctx context.Context, loxiURL *v1.LoxiURL, opts metav1.CreateOptions) (result *v1.LoxiURL, err error) {
	emptyResult := &v1.LoxiURL{}
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateActionWithOptions(loxiurlsResource, loxiURL, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.LoxiURL), err
}

// Update takes the representation of a loxiURL and updates it. Returns the server's representation of the loxiURL, and an error, if there is any.
func (c *FakeLoxiURLs) Update(ctx context.Context, loxiURL *v1.LoxiURL, opts metav1.UpdateOptions) (result *v1.LoxiURL, err error) {
	emptyResult := &v1.LoxiURL{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateActionWithOptions(loxiurlsResource, loxiURL, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.LoxiURL), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeLoxiURLs) UpdateStatus(ctx context.Context, loxiURL *v1.LoxiURL, opts metav1.UpdateOptions) (result *v1.LoxiURL, err error) {
	emptyResult := &v1.LoxiURL{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceActionWithOptions(loxiurlsResource, "status", loxiURL, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.LoxiURL), err
}

// Delete takes name of the loxiURL and deletes it. Returns an error if one occurs.
func (c *FakeLoxiURLs) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(loxiurlsResource, name, opts), &v1.LoxiURL{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLoxiURLs) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionActionWithOptions(loxiurlsResource, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1.LoxiURLList{})
	return err
}

// Patch applies the patch and returns the patched loxiURL.
func (c *FakeLoxiURLs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.LoxiURL, err error) {
	emptyResult := &v1.LoxiURL{}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceActionWithOptions(loxiurlsResource, name, pt, data, opts, subresources...), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.LoxiURL), err
}
