/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	versioned "github.com/loxilb-io/kube-loxilb/pkg/client/clientset/versioned"
	internalinterfaces "github.com/loxilb-io/kube-loxilb/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/loxilb-io/kube-loxilb/pkg/client/listers/bgppolicydefinedsets/v1"
	bgppolicydefinedsetsv1 "github.com/loxilb-io/kube-loxilb/pkg/crds/bgppolicydefinedsets/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// BGPPolicyDefinedSetsServiceInformer provides access to a shared informer and lister for
// BGPPolicyDefinedSetsServices.
type BGPPolicyDefinedSetsServiceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.BGPPolicyDefinedSetsServiceLister
}

type bGPPolicyDefinedSetsServiceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewBGPPolicyDefinedSetsServiceInformer constructs a new informer for BGPPolicyDefinedSetsService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBGPPolicyDefinedSetsServiceInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredBGPPolicyDefinedSetsServiceInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredBGPPolicyDefinedSetsServiceInformer constructs a new informer for BGPPolicyDefinedSetsService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredBGPPolicyDefinedSetsServiceInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BgppolicydefinedsetsV1().BGPPolicyDefinedSetsServices().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BgppolicydefinedsetsV1().BGPPolicyDefinedSetsServices().Watch(context.TODO(), options)
			},
		},
		&bgppolicydefinedsetsv1.BGPPolicyDefinedSetsService{},
		resyncPeriod,
		indexers,
	)
}

func (f *bGPPolicyDefinedSetsServiceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredBGPPolicyDefinedSetsServiceInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *bGPPolicyDefinedSetsServiceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&bgppolicydefinedsetsv1.BGPPolicyDefinedSetsService{}, f.defaultInformer)
}

func (f *bGPPolicyDefinedSetsServiceInformer) Lister() v1.BGPPolicyDefinedSetsServiceLister {
	return v1.NewBGPPolicyDefinedSetsServiceLister(f.Informer().GetIndexer())
}
