/*
Copyright (c) NetLOX Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	egressv1 "github.com/loxilb-io/kube-loxilb/pkg/crds/egress/v1"
	scheme "github.com/loxilb-io/kube-loxilb/pkg/egress-client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// EgressesGetter has a method to return a EgressInterface.
// A group's client should implement this interface.
type EgressesGetter interface {
	Egresses(namespace string) EgressInterface
}

// EgressInterface has methods to work with Egress resources.
type EgressInterface interface {
	Create(ctx context.Context, egress *egressv1.Egress, opts metav1.CreateOptions) (*egressv1.Egress, error)
	Update(ctx context.Context, egress *egressv1.Egress, opts metav1.UpdateOptions) (*egressv1.Egress, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*egressv1.Egress, error)
	List(ctx context.Context, opts metav1.ListOptions) (*egressv1.EgressList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *egressv1.Egress, err error)
	EgressExpansion
}

// egresses implements EgressInterface
type egresses struct {
	*gentype.ClientWithList[*egressv1.Egress, *egressv1.EgressList]
}

// newEgresses returns a Egresses
func newEgresses(c *EgressV1Client, namespace string) *egresses {
	return &egresses{
		gentype.NewClientWithList[*egressv1.Egress, *egressv1.EgressList](
			"egresses",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *egressv1.Egress { return &egressv1.Egress{} },
			func() *egressv1.EgressList { return &egressv1.EgressList{} },
		),
	}
}
