/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// MatchPrefixSetApplyConfiguration represents an declarative configuration of the MatchPrefixSet type for use
// with apply.
type MatchPrefixSetApplyConfiguration struct {
	MatchSetOption *string `json:"matchSetOption,omitempty"`
	PrefixSet      *string `json:"prefixSet,omitempty"`
}

// MatchPrefixSetApplyConfiguration constructs an declarative configuration of the MatchPrefixSet type for use with
// apply.
func MatchPrefixSet() *MatchPrefixSetApplyConfiguration {
	return &MatchPrefixSetApplyConfiguration{}
}

// WithMatchSetOption sets the MatchSetOption field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MatchSetOption field is set to the value of the last call.
func (b *MatchPrefixSetApplyConfiguration) WithMatchSetOption(value string) *MatchPrefixSetApplyConfiguration {
	b.MatchSetOption = &value
	return b
}

// WithPrefixSet sets the PrefixSet field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrefixSet field is set to the value of the last call.
func (b *MatchPrefixSetApplyConfiguration) WithPrefixSet(value string) *MatchPrefixSetApplyConfiguration {
	b.PrefixSet = &value
	return b
}
