/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	multiclusterlbservicev1 "github.com/loxilb-io/kube-loxilb/pkg/crds/multiclusterlbservice/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMultiClusterLBServices implements MultiClusterLBServiceInterface
type FakeMultiClusterLBServices struct {
	Fake *FakeMulticlusterV1
}

var multiclusterlbservicesResource = schema.GroupVersionResource{Group: "multicluster.loxilb.io", Version: "v1", Resource: "multiclusterlbservices"}

var multiclusterlbservicesKind = schema.GroupVersionKind{Group: "multicluster.loxilb.io", Version: "v1", Kind: "MultiClusterLBService"}

// Get takes name of the multiClusterLBService, and returns the corresponding multiClusterLBService object, and an error if there is any.
func (c *FakeMultiClusterLBServices) Get(ctx context.Context, name string, options v1.GetOptions) (result *multiclusterlbservicev1.MultiClusterLBService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(multiclusterlbservicesResource, name), &multiclusterlbservicev1.MultiClusterLBService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*multiclusterlbservicev1.MultiClusterLBService), err
}

// List takes label and field selectors, and returns the list of MultiClusterLBServices that match those selectors.
func (c *FakeMultiClusterLBServices) List(ctx context.Context, opts v1.ListOptions) (result *multiclusterlbservicev1.MultiClusterLBServiceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(multiclusterlbservicesResource, multiclusterlbservicesKind, opts), &multiclusterlbservicev1.MultiClusterLBServiceList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &multiclusterlbservicev1.MultiClusterLBServiceList{ListMeta: obj.(*multiclusterlbservicev1.MultiClusterLBServiceList).ListMeta}
	for _, item := range obj.(*multiclusterlbservicev1.MultiClusterLBServiceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested multiClusterLBServices.
func (c *FakeMultiClusterLBServices) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(multiclusterlbservicesResource, opts))
}

// Create takes the representation of a multiClusterLBService and creates it.  Returns the server's representation of the multiClusterLBService, and an error, if there is any.
func (c *FakeMultiClusterLBServices) Create(ctx context.Context, multiClusterLBService *multiclusterlbservicev1.MultiClusterLBService, opts v1.CreateOptions) (result *multiclusterlbservicev1.MultiClusterLBService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(multiclusterlbservicesResource, multiClusterLBService), &multiclusterlbservicev1.MultiClusterLBService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*multiclusterlbservicev1.MultiClusterLBService), err
}

// Update takes the representation of a multiClusterLBService and updates it. Returns the server's representation of the multiClusterLBService, and an error, if there is any.
func (c *FakeMultiClusterLBServices) Update(ctx context.Context, multiClusterLBService *multiclusterlbservicev1.MultiClusterLBService, opts v1.UpdateOptions) (result *multiclusterlbservicev1.MultiClusterLBService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(multiclusterlbservicesResource, multiClusterLBService), &multiclusterlbservicev1.MultiClusterLBService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*multiclusterlbservicev1.MultiClusterLBService), err
}

// Delete takes name of the multiClusterLBService and deletes it. Returns an error if one occurs.
func (c *FakeMultiClusterLBServices) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(multiclusterlbservicesResource, name), &multiclusterlbservicev1.MultiClusterLBService{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMultiClusterLBServices) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(multiclusterlbservicesResource, listOpts)

	_, err := c.Fake.Invokes(action, &multiclusterlbservicev1.MultiClusterLBServiceList{})
	return err
}

// Patch applies the patch and returns the patched multiClusterLBService.
func (c *FakeMultiClusterLBServices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *multiclusterlbservicev1.MultiClusterLBService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(multiclusterlbservicesResource, name, pt, data, subresources...), &multiclusterlbservicev1.MultiClusterLBService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*multiclusterlbservicev1.MultiClusterLBService), err
}
