/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	bgppolicydefinitionv1 "github.com/loxilb-io/kube-loxilb/pkg/bgp-client/applyconfiguration/bgppolicydefinition/v1"
	v1 "github.com/loxilb-io/kube-loxilb/pkg/crds/bgppolicydefinition/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBGPPolicyDefinitionServices implements BGPPolicyDefinitionServiceInterface
type FakeBGPPolicyDefinitionServices struct {
	Fake *FakeBgppolicydefinitionV1
}

var bgppolicydefinitionservicesResource = v1.SchemeGroupVersion.WithResource("bgppolicydefinitionservices")

var bgppolicydefinitionservicesKind = v1.SchemeGroupVersion.WithKind("BGPPolicyDefinitionService")

// Get takes name of the bGPPolicyDefinitionService, and returns the corresponding bGPPolicyDefinitionService object, and an error if there is any.
func (c *FakeBGPPolicyDefinitionServices) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.BGPPolicyDefinitionService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(bgppolicydefinitionservicesResource, name), &v1.BGPPolicyDefinitionService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.BGPPolicyDefinitionService), err
}

// List takes label and field selectors, and returns the list of BGPPolicyDefinitionServices that match those selectors.
func (c *FakeBGPPolicyDefinitionServices) List(ctx context.Context, opts metav1.ListOptions) (result *v1.BGPPolicyDefinitionServiceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(bgppolicydefinitionservicesResource, bgppolicydefinitionservicesKind, opts), &v1.BGPPolicyDefinitionServiceList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.BGPPolicyDefinitionServiceList{ListMeta: obj.(*v1.BGPPolicyDefinitionServiceList).ListMeta}
	for _, item := range obj.(*v1.BGPPolicyDefinitionServiceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested bGPPolicyDefinitionServices.
func (c *FakeBGPPolicyDefinitionServices) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(bgppolicydefinitionservicesResource, opts))
}

// Create takes the representation of a bGPPolicyDefinitionService and creates it.  Returns the server's representation of the bGPPolicyDefinitionService, and an error, if there is any.
func (c *FakeBGPPolicyDefinitionServices) Create(ctx context.Context, bGPPolicyDefinitionService *v1.BGPPolicyDefinitionService, opts metav1.CreateOptions) (result *v1.BGPPolicyDefinitionService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(bgppolicydefinitionservicesResource, bGPPolicyDefinitionService), &v1.BGPPolicyDefinitionService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.BGPPolicyDefinitionService), err
}

// Update takes the representation of a bGPPolicyDefinitionService and updates it. Returns the server's representation of the bGPPolicyDefinitionService, and an error, if there is any.
func (c *FakeBGPPolicyDefinitionServices) Update(ctx context.Context, bGPPolicyDefinitionService *v1.BGPPolicyDefinitionService, opts metav1.UpdateOptions) (result *v1.BGPPolicyDefinitionService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(bgppolicydefinitionservicesResource, bGPPolicyDefinitionService), &v1.BGPPolicyDefinitionService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.BGPPolicyDefinitionService), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBGPPolicyDefinitionServices) UpdateStatus(ctx context.Context, bGPPolicyDefinitionService *v1.BGPPolicyDefinitionService, opts metav1.UpdateOptions) (*v1.BGPPolicyDefinitionService, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(bgppolicydefinitionservicesResource, "status", bGPPolicyDefinitionService), &v1.BGPPolicyDefinitionService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.BGPPolicyDefinitionService), err
}

// Delete takes name of the bGPPolicyDefinitionService and deletes it. Returns an error if one occurs.
func (c *FakeBGPPolicyDefinitionServices) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(bgppolicydefinitionservicesResource, name, opts), &v1.BGPPolicyDefinitionService{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBGPPolicyDefinitionServices) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(bgppolicydefinitionservicesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1.BGPPolicyDefinitionServiceList{})
	return err
}

// Patch applies the patch and returns the patched bGPPolicyDefinitionService.
func (c *FakeBGPPolicyDefinitionServices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.BGPPolicyDefinitionService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(bgppolicydefinitionservicesResource, name, pt, data, subresources...), &v1.BGPPolicyDefinitionService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.BGPPolicyDefinitionService), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied bGPPolicyDefinitionService.
func (c *FakeBGPPolicyDefinitionServices) Apply(ctx context.Context, bGPPolicyDefinitionService *bgppolicydefinitionv1.BGPPolicyDefinitionServiceApplyConfiguration, opts metav1.ApplyOptions) (result *v1.BGPPolicyDefinitionService, err error) {
	if bGPPolicyDefinitionService == nil {
		return nil, fmt.Errorf("bGPPolicyDefinitionService provided to Apply must not be nil")
	}
	data, err := json.Marshal(bGPPolicyDefinitionService)
	if err != nil {
		return nil, err
	}
	name := bGPPolicyDefinitionService.Name
	if name == nil {
		return nil, fmt.Errorf("bGPPolicyDefinitionService.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(bgppolicydefinitionservicesResource, *name, types.ApplyPatchType, data), &v1.BGPPolicyDefinitionService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.BGPPolicyDefinitionService), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeBGPPolicyDefinitionServices) ApplyStatus(ctx context.Context, bGPPolicyDefinitionService *bgppolicydefinitionv1.BGPPolicyDefinitionServiceApplyConfiguration, opts metav1.ApplyOptions) (result *v1.BGPPolicyDefinitionService, err error) {
	if bGPPolicyDefinitionService == nil {
		return nil, fmt.Errorf("bGPPolicyDefinitionService provided to Apply must not be nil")
	}
	data, err := json.Marshal(bGPPolicyDefinitionService)
	if err != nil {
		return nil, err
	}
	name := bGPPolicyDefinitionService.Name
	if name == nil {
		return nil, fmt.Errorf("bGPPolicyDefinitionService.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(bgppolicydefinitionservicesResource, *name, types.ApplyPatchType, data, "status"), &v1.BGPPolicyDefinitionService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.BGPPolicyDefinitionService), err
}
