/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	bgppolicyapplyv1 "github.com/loxilb-io/kube-loxilb/pkg/client/applyconfiguration/bgppolicyapply/v1"
	v1 "github.com/loxilb-io/kube-loxilb/pkg/crds/bgppolicyapply/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBGPPolicyApplyServices implements BGPPolicyApplyServiceInterface
type FakeBGPPolicyApplyServices struct {
	Fake *FakeBgppolicyapplyV1
}

var bgppolicyapplyservicesResource = v1.SchemeGroupVersion.WithResource("bgppolicyapplyservices")

var bgppolicyapplyservicesKind = v1.SchemeGroupVersion.WithKind("BGPPolicyApplyService")

// Get takes name of the bGPPolicyApplyService, and returns the corresponding bGPPolicyApplyService object, and an error if there is any.
func (c *FakeBGPPolicyApplyServices) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.BGPPolicyApplyService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(bgppolicyapplyservicesResource, name), &v1.BGPPolicyApplyService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.BGPPolicyApplyService), err
}

// List takes label and field selectors, and returns the list of BGPPolicyApplyServices that match those selectors.
func (c *FakeBGPPolicyApplyServices) List(ctx context.Context, opts metav1.ListOptions) (result *v1.BGPPolicyApplyServiceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(bgppolicyapplyservicesResource, bgppolicyapplyservicesKind, opts), &v1.BGPPolicyApplyServiceList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.BGPPolicyApplyServiceList{ListMeta: obj.(*v1.BGPPolicyApplyServiceList).ListMeta}
	for _, item := range obj.(*v1.BGPPolicyApplyServiceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested bGPPolicyApplyServices.
func (c *FakeBGPPolicyApplyServices) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(bgppolicyapplyservicesResource, opts))
}

// Create takes the representation of a bGPPolicyApplyService and creates it.  Returns the server's representation of the bGPPolicyApplyService, and an error, if there is any.
func (c *FakeBGPPolicyApplyServices) Create(ctx context.Context, bGPPolicyApplyService *v1.BGPPolicyApplyService, opts metav1.CreateOptions) (result *v1.BGPPolicyApplyService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(bgppolicyapplyservicesResource, bGPPolicyApplyService), &v1.BGPPolicyApplyService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.BGPPolicyApplyService), err
}

// Update takes the representation of a bGPPolicyApplyService and updates it. Returns the server's representation of the bGPPolicyApplyService, and an error, if there is any.
func (c *FakeBGPPolicyApplyServices) Update(ctx context.Context, bGPPolicyApplyService *v1.BGPPolicyApplyService, opts metav1.UpdateOptions) (result *v1.BGPPolicyApplyService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(bgppolicyapplyservicesResource, bGPPolicyApplyService), &v1.BGPPolicyApplyService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.BGPPolicyApplyService), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBGPPolicyApplyServices) UpdateStatus(ctx context.Context, bGPPolicyApplyService *v1.BGPPolicyApplyService, opts metav1.UpdateOptions) (*v1.BGPPolicyApplyService, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(bgppolicyapplyservicesResource, "status", bGPPolicyApplyService), &v1.BGPPolicyApplyService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.BGPPolicyApplyService), err
}

// Delete takes name of the bGPPolicyApplyService and deletes it. Returns an error if one occurs.
func (c *FakeBGPPolicyApplyServices) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(bgppolicyapplyservicesResource, name, opts), &v1.BGPPolicyApplyService{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBGPPolicyApplyServices) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(bgppolicyapplyservicesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1.BGPPolicyApplyServiceList{})
	return err
}

// Patch applies the patch and returns the patched bGPPolicyApplyService.
func (c *FakeBGPPolicyApplyServices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.BGPPolicyApplyService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(bgppolicyapplyservicesResource, name, pt, data, subresources...), &v1.BGPPolicyApplyService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.BGPPolicyApplyService), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied bGPPolicyApplyService.
func (c *FakeBGPPolicyApplyServices) Apply(ctx context.Context, bGPPolicyApplyService *bgppolicyapplyv1.BGPPolicyApplyServiceApplyConfiguration, opts metav1.ApplyOptions) (result *v1.BGPPolicyApplyService, err error) {
	if bGPPolicyApplyService == nil {
		return nil, fmt.Errorf("bGPPolicyApplyService provided to Apply must not be nil")
	}
	data, err := json.Marshal(bGPPolicyApplyService)
	if err != nil {
		return nil, err
	}
	name := bGPPolicyApplyService.Name
	if name == nil {
		return nil, fmt.Errorf("bGPPolicyApplyService.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(bgppolicyapplyservicesResource, *name, types.ApplyPatchType, data), &v1.BGPPolicyApplyService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.BGPPolicyApplyService), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeBGPPolicyApplyServices) ApplyStatus(ctx context.Context, bGPPolicyApplyService *bgppolicyapplyv1.BGPPolicyApplyServiceApplyConfiguration, opts metav1.ApplyOptions) (result *v1.BGPPolicyApplyService, err error) {
	if bGPPolicyApplyService == nil {
		return nil, fmt.Errorf("bGPPolicyApplyService provided to Apply must not be nil")
	}
	data, err := json.Marshal(bGPPolicyApplyService)
	if err != nil {
		return nil, err
	}
	name := bGPPolicyApplyService.Name
	if name == nil {
		return nil, fmt.Errorf("bGPPolicyApplyService.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(bgppolicyapplyservicesResource, *name, types.ApplyPatchType, data, "status"), &v1.BGPPolicyApplyService{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.BGPPolicyApplyService), err
}
