{
 "title": "LoxiLB",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "LB Rule Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lb_rule_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Healthy Endpoint Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "healthy_host_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Unhealthy Endpoint Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "unhealthy_host_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active TCP Session Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_flow_count_tcp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active UDP Session Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_flow_count_udp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active SCTP Session Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_flow_count_sctp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Traffic Processed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(processed_bytes[1m]))*8",
     "legendFormat": "Total Traffic"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_conntrack_count", "legendFormat": "Active Connections" }
   ]
  },
  {
   "title": "Total Throughput (BPS)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "expr": "rate(processed_bytes[1m])*8", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Processed Packets(PPS)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    { "expr": "rate(processed_packets[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Top 5 Endpoints by Traffic",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(rate(lb_rule_interaction_bytes[1m])*8) by (dip))",
     "legendFormat": "{{dip}}"
    }
   ]
  },
  {
   "title": "Top 5 Endpoint Distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(endpoint_load_dists_per_service) by (dip))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Top 5 Service  by Traffic",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(rate(lb_rule_interaction_bytes[1m])*8) by (service))",
     "legendFormat": "{{dip}}"
    }
   ]
  },
  {
   "title": "Traffic Distribution by Service",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(total_load_dists_per_service) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Top 5 Drops by FW Rule",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(rate(total_fw_drops_per_rule[1m])) by (fw_rule))",
     "legendFormat": "{{fw_rule}}"
    }
   ]
  },
  {
   "title": "Total Drops by FW rule",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(total_fw_drops_per_rule[1m])) by (fw_rule)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "New Flow Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    { "expr": "new_flow_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Flow Count TCP",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "active_flow_count_tcp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Flow Count UDP",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "active_flow_count_udp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Flow Count SCTP",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "active_flow_count_sctp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "TCP Throughput (BPS)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(processed_tcp_bytes[1m]) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UDP Throughput (BPS)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(processed_udp_bytes[1m]) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SCTP Throughput (BPS)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(processed_sctp_bytes[1m]) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "rate(total_requests[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests Per Service",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(total_requests_per_service[1m])) by (service)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    { "expr": "rate(total_errors[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Errors Per Service",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(total_errors_per_service[1m])) by (service)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "LoxiLB Network View",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "loxilb",
    "label": "loxilb",
    "query": "loxilb-lb-service.kube-system.svc.cluster.local:11111"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Ports",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "data": "{\"lbAttr\":[{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"20.20.20.1\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.254\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.3\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}}]}\n",
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"portAttr\"\n| count\n",
     "url": "http://${loxilb}/netlox/v1/config/port/all",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Number of Interfaces",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "data": "{\"lbAttr\":[{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"20.20.20.1\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.254\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.3\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}}]}\n",
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"ipAttr\"\n| project \"Name\"=\"dev\",\"IP Address\"=\"ip\",\"Sync\"=\"sync\"\n| count\n",
     "url": "http://${loxilb}/netlox/v1/config/ipv4address/all",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Number ARP Tables",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "data": "{\"lbAttr\":[{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"20.20.20.1\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.254\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.3\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}}]}\n",
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"neighborAttr\"\n| count",
     "url": "http://${loxilb}/netlox/v1/config/neighbor/all",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Number of VLAN Tables",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "data": "{\"lbAttr\":[{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"20.20.20.1\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.254\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.3\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}}]}\n",
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"vlanAttr\"\n| mv-expand \"vlan\"=\"member\"\n| count\n",
     "url": "http://${loxilb}/netlox/v1/config/vlan/all",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Number BGP Neighbors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "data": "{\"lbAttr\":[{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"20.20.20.1\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.254\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.3\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}}]}\n",
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"bgpNeiAttr\"\n| count",
     "url": "http://${loxilb}/netlox/v1/config/bgp/neigh/all",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Number of ACL Tables",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "data": "{\"lbAttr\":[{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"20.20.20.1\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.254\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.3\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}}]}\n",
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"fwAttr\"\n| count\n",
     "url": "http://${loxilb}/netlox/v1/config/firewall/all",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "HA State Table",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "data": "{\"lbAttr\":[{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"20.20.20.1\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.254\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.3\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}}]}\n",
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"Attr\"\n| project \"Instance\"=\"instance\",\"VIP\"=\"vip\",\"State\"=\"state\",\"Sync\"=\"sync\"\n",
     "url": "http://${loxilb}/netlox/v1/config/cistate/all",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Port Table",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "data": "{\"lbAttr\":[{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"20.20.20.1\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.254\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.3\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}}]}\n",
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"portAttr\"\n| project \"Number\"=\"portNo\",\"Name\"=\"portName\",\"Link\"=\"portHardwareInformation.link\", \"MAC Address\"=\"portHardwareInformation.macAddress\", \"MTU\"=\"portHardwareInformation.mtu\"\n| order by \"Number\" asc\n",
     "url": "http://${loxilb}/netlox/v1/config/port/all",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Interface Table",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "data": "{\"lbAttr\":[{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"20.20.20.1\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.254\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.3\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}}]}\n",
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"ipAttr\"\n| mv-expand \"ip\"=\"ipAddress\"\n| project \"Name\"=\"dev\",\"IP Address\"=\"ip\",\"Sync\"=\"sync\"\n| order by \"Name\" desc\n\n",
     "url": "http://${loxilb}/netlox/v1/config/ipv4address/all",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "ARP Table",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "data": "{\"lbAttr\":[{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"20.20.20.1\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.254\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.3\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}}]}\n",
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"neighborAttr\"\n| project \"IP Address\"=\"ipAddress\",\"MAC Address\"=\"macAddress\",\"Interface\"=\"dev\"\n| order by \"IP Address\" asc",
     "url": "http://${loxilb}/netlox/v1/config/neighbor/all",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Route Table",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "data": "{\"lbAttr\":[{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"20.20.20.1\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.254\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.3\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}}]}\n",
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"routeAttr\"\n| project \"Destination\"=\"destinationIPNet\",\"Flags\"=\"flags\",\"Bytes\"=\"statistic.bytes\",\"Packets\"=\"statistic.packets\"\n| order by \"Flags\" asc\n",
     "url": "http://${loxilb}/netlox/v1/config/route/all",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "FDB Table",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "data": "{\"lbAttr\":[{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"20.20.20.1\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.254\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.3\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}}]}\n",
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"fdbAttr\"\n| project \"MAC Address\"=\"macAddress\",\"Interface\"=\"dev\"\n| order by \"MAC Address\" asc",
     "url": "http://${loxilb}/netlox/v1/config/fdb/all",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "VLAN Table",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "data": "{\"lbAttr\":[{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"20.20.20.1\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.254\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.3\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}}]}\n",
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"vlanAttr\"\n| mv-expand \"vlan\"=\"member\"\n| project \"VID\"=\"vid\", \"Name\"=\"dev\", \"Member_Port\"=\"vlan.dev\", \"Member_Tagging\"=\"vlan.tagged\", \"Rx_Bytes\"=\"vlanStatistic.inBytes\", \"Rx_Packets\"=\"vlanStatistic.inPackets\", \"Tx_Bytes\"=\"vlanStatistic.outBytes\", \"Tx_Packets\"=\"vlanStatistic.outPackets\"\n",
     "url": "http://${loxilb}/netlox/v1/config/vlan/all",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "BGP Neighbor Table",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "data": "{\"lbAttr\":[{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"20.20.20.1\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.254\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.3\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}}]}\n",
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"bgpNeiAttr\"\n| project \"Remote AS\"=\"remoteAs\", \"IP Address\"=\"ipAddress\", \"State\"=\"state\", \"Up/Down Time\"=\"updowntime\"\n| order by \"Remote AS\" asc\n",
     "url": "http://${loxilb}/netlox/v1/config/bgp/neigh/all",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "ACL Table",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {
     "data": "{\"lbAttr\":[{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"20.20.20.1\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.254\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.3\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}}]}\n",
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"fwAttr\"\n| project \"Match_Port\"=\"ruleArguments.portName\", \"Match_Protocol\"=\"ruleArguments.protocol\", \"Match_Source_IP\"=\"ruleArguments.sourceIP\", \"Match_Destination_IP\"=\"ruleArguments.destinationIP\", \"Match_Source_Port_Min\"=\"ruleArguments.minSourcePort\", \"Match_Source_Port_Max\"=\"ruleArguments.maxSourcePort\", \"Match_Destination_Port_Min\"=\"ruleArguments.minDestinationPort\", \"Match_Destination_Port_Max\"=\"ruleArguments.maxDestinationPort\", \"Action_Drop\"=\"opts.drop\", \"Action_Trap\"=\"opts.trap\", \"Action_Redirect\"=\"opts.redirect\", \"Action_Redirect_Port\"=\"opts.redirectPortName\", \"Action_Allow\"=\"opts.allow\", \"Action_Mark\"=\"opts.fwMark\"\n",
     "url": "http://${loxilb}/netlox/v1/config/firewall/all",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "BFD Table",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 93 },
   "targets": [
    {
     "data": "{\"lbAttr\":[{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"20.20.20.1\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.254\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.3\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}}]}\n",
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"Attr\"\n| project \"Instance\"=\"instance\", \"Source IP\"=\"sourceIP\", \"Destination IP\"=\"remoteIp\", \"Port\"=\"port\", \"Interval\"=\"interval\", \"Retry Counts\"=\"retryCount\", \"State\"=\"state\"\n",
     "url": "http://${loxilb}/netlox/v1/config/bfd/all",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  }
 ]
}
{
 "title": "LoxiLB Traffic Management",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "loxilb",
    "label": "loxilb",
    "query": "loxilb-lb-service.kube-system.svc.cluster.local:11111"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of LB Policies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "data": "{\"lbAttr\":[{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"20.20.20.1\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.254\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.3\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}}]}\n",
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"lbAttr\"\n| summarize \"total_count\"=count() by \"serviceArguments\"\n| project \"total_count\"\n",
     "url": "http://${loxilb}/netlox/v1/config/loadbalancer/all",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Number of LB Endpoints",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "data": "{\"lbAttr\":[{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"20.20.20.1\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.254\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.3\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}}]}\n",
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"Attr\"\n| count\n",
     "url": "http://${loxilb}/netlox/v1/config/endpoint/all",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Number of LB Healthy Endpoints",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "data": "{\"lbAttr\":[{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"20.20.20.1\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.254\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.3\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}}]}\n",
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"Attr\"\n| where \"currState\" == 'ok'\n| count\n",
     "url": "http://${loxilb}/netlox/v1/config/endpoint/all",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "HA State Table",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "data": "{\"lbAttr\":[{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"20.20.20.1\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.254\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.3\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}}]}\n",
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"Attr\"\n| project \"VIP\"=\"vip\", \"Instance\"=\"instance\",\"State\"=\"state\",\"Sync\"=\"sync\"\n| order by \"VIP\" asc\n",
     "url": "http://${loxilb}/netlox/v1/config/cistate/all",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Number of LB UnHealthy Endpoints",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "data": "{\"lbAttr\":[{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"20.20.20.1\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.254\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.3\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}}]}\n",
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"Attr\"\n| where \"currState\" != 'ok'\n| count\n",
     "url": "http://${loxilb}/netlox/v1/config/endpoint/all",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Number of QoS Rules",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "data": "{\"lbAttr\":[{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"20.20.20.1\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.254\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.3\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}}]}\n",
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"polAttr\"\n| count\n",
     "url": "http://${loxilb}/netlox/v1/config/policy/all",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Number of Mirror Rules",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "data": "{\"lbAttr\":[{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"20.20.20.1\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.254\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.3\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}}]}\n",
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"mirrAttr\"\n| count\n",
     "url": "http://${loxilb}/netlox/v1/config/mirror/all",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "LB Configuration Parameters",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "data": "{\"lbAttr\":[{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"20.20.20.1\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.254\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.3\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}}]}\n",
     "parser": "simple",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"Attr\"\n| project \"Name\"=\"name\",\"IP\"=\"hostName\",\"Probe Port\"=\"probePort\",\"Probe Type\"=\"probeType\",\"State\"=\"currState\"\n| order by \"Name\" asc\n",
     "url": "http://${loxilb}/netlox/v1/config/params",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Top 10 Traffic pair ",
   "type": "netsage-sankey-panel",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"lb_rule_interaction_bytes\"\n| project \"Source\"=\"sip\",\"Service\"=\"service\",\"Destiantion\"=\"dip\",\"Traffic\"=\"value\"\n| order by \"Traffic\" desc\n| limit 10\n\n",
     "url": "http://${loxilb}/netlox/v1/metrics/lbprocessedtraffic",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Service Graph",
   "type": "nodeGraph",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"nodes\"",
     "url": "http://${loxilb}/netlox/v1/nodegraph/all",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"edges\"",
     "url": "http://${loxilb}/netlox/v1/nodegraph/all",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "LB Policy Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "data": "{\"lbAttr\":[{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"20.20.20.1\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.254\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.3\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}}]}\n",
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"lbAttr\"\n| mv-expand \"endpoint\"=\"endpoints\"\n| project \"LB_VIP\"=\"serviceArguments.externalIP\", \"LB_Port\"=\"serviceArguments.port\", \"LB_Protocol\"=\"serviceArguments.protocol\", \"LB_Timeout\"=\"serviceArguments.inactiveTimeOut\", \"endpoint_ip\"=\"endpoint.endpointIP\", \"endpoint_targetPort\"=\"endpoint.targetPort\", \"endpoint_state\"=\"endpoint.state\", \"endpoint_weight\"=\"endpoint.weight\"\n",
     "url": "http://${loxilb}/netlox/v1/config/loadbalancer/all",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "LB Endpoint Table",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "data": "{\"lbAttr\":[{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"20.20.20.1\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.254\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.3\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}}]}\n",
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"Attr\"\n| project \"Name\"=\"name\",\"IP\"=\"hostName\",\"Probe Port\"=\"probePort\",\"Probe Type\"=\"probeType\",\"State\"=\"currState\"\n| order by \"Name\" asc\n",
     "url": "http://${loxilb}/netlox/v1/config/endpoint/all",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Connection Track Table",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "data": "{\"lbAttr\":[{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"20.20.20.1\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.254\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.3\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}}]}\n",
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"ctAttr\"\n| project \"Source IP\"=\"sourceIP\", \"Destination IP\"=\"destinationIP\", \"Source Port\"=\"sourcePort\", \"Destination Port\"=\"destinationPort\", \"Protocol\"=\"protocol\", \"Server Name\"=\"servName\", \"CT State\"=\"conntrackState\", \"CT Act\"=\"conntrackAct\", \"Bytes\"=\"bytes\", \"Packets\"=\"packets\"\n\n",
     "url": "http://${loxilb}/netlox/v1/config/conntrack/all",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "QoS Configuration Table",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "data": "{\"lbAttr\":[{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"20.20.20.1\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.254\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.3\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}}]}\n",
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"polAttr\"\n| project \"ID\"=\"policyIdent\",\"Type\"=\"policyInfo.type\",\"Committed Rate\"=\"policyInfo.committedInfoRate\", \"Peak Rate\"=\"policyInfo.peakInfoRate\", \"Block Size\"=\"policyInfo.committedBlkSize\", \"Excess Block Size\"=\"policyInfo.excessBlkSize\", \"Target Attachment\"=\"targetObject.attachment\", \"Target Policy Name\"=\"targetObject.polObjName\"\n| order by \"ID\" asc\n",
     "url": "http://${loxilb}/netlox/v1/config/policy/all",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Mirror Configuration Table",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "data": "{\"lbAttr\":[{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"20.20.20.1\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.254\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}},{\"endpoints\":[{\"counter\":\"0:0\",\"endpointIP\":\"31.31.31.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"32.32.32.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1},{\"counter\":\"0:0\",\"endpointIP\":\"33.33.33.1\",\"state\":\"active\",\"targetPort\":8080,\"weight\":1}],\"secondaryIPs\":null,\"serviceArguments\":{\"externalIP\":\"10.10.10.3\",\"inactiveTimeOut\":240,\"port\":2020,\"protocol\":\"tcp\"}}]}\n",
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"mirrAttr\"\n| project \"ID\"=\"mirrorIdent\",\"Type\"=\"mirrorInfo.type\",\"Port\"=\"mirrorInfo.port\", \"VLAN\"=\"mirrorInfo.vlan\", \"Source IP\"=\"mirrorInfo.sourceIP\", \"Destination IP\"=\"mirrorInfo.remoteIP\", \"Tunnel ID\"=\"mirrorInfo.tunnelID\", \"Target Policy Name\"=\"targetObject.mirrObjName\"\n| order by \"ID\" asc\n",
     "url": "http://${loxilb}/netlox/v1/config/mirror/all",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "LoxiLB  Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "{job=\"loxilb-app-logs\"} |= ``"
    }
   ]
  },
  {
   "title": "Kube-LoxiLB Logs ",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "{job=\"kube-loxilb-app-logs\"} |= ``"
    }
   ]
  }
 ]
}