/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	klbcrdsloxiurlv1 "github.com/loxilb-io/kube-loxilb/pkg/crds/loxiurl/v1"
	versioned "github.com/loxilb-io/kube-loxilb/pkg/klb-client/clientset/versioned"
	internalinterfaces "github.com/loxilb-io/kube-loxilb/pkg/klb-client/informers/externalversions/internalinterfaces"
	loxiurlv1 "github.com/loxilb-io/kube-loxilb/pkg/klb-client/listers/loxiurl/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// LoxiURLInformer provides access to a shared informer and lister for
// LoxiURLs.
type LoxiURLInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() loxiurlv1.LoxiURLLister
}

type loxiURLInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewLoxiURLInformer constructs a new informer for LoxiURL type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewLoxiURLInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredLoxiURLInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredLoxiURLInformer constructs a new informer for LoxiURL type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredLoxiURLInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LoxiurlV1().LoxiURLs().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LoxiurlV1().LoxiURLs().Watch(context.TODO(), options)
			},
		},
		&klbcrdsloxiurlv1.LoxiURL{},
		resyncPeriod,
		indexers,
	)
}

func (f *loxiURLInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredLoxiURLInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *loxiURLInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&klbcrdsloxiurlv1.LoxiURL{}, f.defaultInformer)
}

func (f *loxiURLInformer) Lister() loxiurlv1.LoxiURLLister {
	return loxiurlv1.NewLoxiURLLister(f.Informer().GetIndexer())
}
